name: Deploy
run-name: Peanut Gallery API Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: zip
        run: npm run zip
      - run: ls
      - name: authenticate with aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::256470578440:role/PeanutGalleryGithubActionsAPIDeployer
